### ISSUE TITLE
Undefined variable `$item`

### ISSUE THREAD

**Issue by zorglube** [kd2org/opodsync#42]
Hello, I deployed a oPodSync on Clever-Cloud, I did it like that : https://blog.broncotoxique.com/2024/03/08/deploy-micro-gpodder-server-on-clever-cloud/

I updated to the last version of oPodSync (commitId: eb22a6ec698df3bd7ec2a86f8e6bebdd60a39323) and I have this stacktrace when I click `Update all feeds metadata` 

```
[14-May-2024 11:29:17 UTC] ErrorException: Undefined variable $item in /home/bas/XXXXXXXX/server/inc/Feed.php:129
Stack trace:
#0 /home/bas/XXXXXXXX/server/inc/Feed.php(129): {closure}(2, 'Undefined varia...', '/home/bas/app_2...', 129)
#1 /home/bas/XXXXXXXX/server/inc/GPodder.php(175): Feed->fetch()
#2 /home/bas/XXXXXXXX/server/inc/GPodder.php(222): GPodder->updateFeedForSubscription(6)
#3 /home/bas/XXXXXXXX/server/index.php(154): GPodder->updateAllFeeds()
#4 {main}
[14-May-2024 11:29:17 UTC] Array
(
    [0] => Array
        (
            [file] => /home/bas/XXXXXXXX/server/inc/Feed.php
            [line] => 129
            [function] => {closure}
            [args] => Array
                (
                    [0] => 2
                    [1] => Undefined variable $item
                    [2] => /home/bas/XXXXXXXX/server/inc/Feed.php
                    [3] => 129
                )

        )

    [1] => Array
        (
            [file] => /home/bas/XXXXXXXX/server/inc/GPodder.php
            [line] => 175
            [function] => fetch
            [class] => Feed
            [object] => Feed Object
                (
                    [feed_url] => https://feed.ausha.co/BG6gxT83Mk7l
                    [image_url] => 
                    [url] => 
                    [language] => 
                    [title] => 
                    [description] => 
                    [pubdate] => 
                    [last_fetch] => 1715686157
                    [episodes:protected] => Array
                        (
                        )

                )

            [type] => ->
            [args] => Array
                (
                )

        )

    [2] => Array
        (
            [file] => /home/bas/XXXXXXXX/server/inc/GPodder.php
            [line] => 222
            [function] => updateFeedForSubscription
            [class] => GPodder
            [object] => GPodder Object
                (
                    [db:protected] => DB Object
                        (
                            [statements:protected] => Array
                                (
                                    [123d5d8619f9874788d32d4ec1ee0e34] => SQLite3Stmt Object
                                        (
                                        )

                                    [f92c7840fbedabdface91470010ae5e3] => SQLite3Stmt Object
                                        (
                                        )

                                    [aa4a0d6ccd6393d53549cb98b2b15bdf] => SQLite3Stmt Object
                                        (
                                        )

                                    [2f9899721f92107afe4e2653a7096232] => SQLite3Stmt Object
                                        (
                                        )

                                )

                        )

                    [user] => stdClass Object
                        (
                            [id] => 1
                            [name] => zorglube
                            [password] => $2y$10$RD62D.r82JprugTRpf0h7OxhsatA/YdB.DdB.ri7.lu0.hm1/gCaC
                        )

                )

            [type] => ->
            [args] => Array
                (
                    [0] => 6
                )

        )

    [3] => Array
        (
            [file] => /home/bas/XXXXXXXX/server/index.php
            [line] => 154
            [function] => updateAllFeeds
            [class] => GPodder
            [object] => GPodder Object
                (
                    [db:protected] => DB Object
                        (
                            [statements:protected] => Array
                                (
                                    [123d5d8619f9874788d32d4ec1ee0e34] => SQLite3Stmt Object
                                        (
                                        )

                                    [f92c7840fbedabdface91470010ae5e3] => SQLite3Stmt Object
                                        (
                                        )

                                    [aa4a0d6ccd6393d53549cb98b2b15bdf] => SQLite3Stmt Object
                                        (
                                        )

                                    [2f9899721f92107afe4e2653a7096232] => SQLite3Stmt Object
                                        (
                                        )

                                )

                        )

                    [user] => stdClass Object
                        (
                            [id] => 1
                            [name] => zorglube
                            [password] => $2y$10$RD62D.r82JprugTRpf0h7OxhsatA/YdB.DdB.ri7.lu0.hm1/gCaC
                        )

                )

            [type] => ->
            [args] => Array
                (
                )

        )

)
```

**Comment by zorglube** [comment]
Damn !  you're fast !!!
