### ISSUE TITLE
Missing title for... 

### ISSUE THREAD

**Issue by zorglube** [kd2org/opodsync#43]
Hello, I deployed a oPodSync on Clever-Cloud, I did it like that : https://blog.broncotoxique.com/2024/03/08/deploy-micro-gpodder-server-on-clever-cloud/

I updated to the last version of oPodSync (commitId: https://github.com/kd2org/opodsync/commit/b5466b0cd2dfc72d5fabd2123a35cc08c574a7fe) and I have this stacktrace when I click `Update all feeds metadata`

```
LogicException: Missing title for: https://feed.ausha.co/BG6gxT83Mk7l in /home/bas/XXXXXXXXXX/server/inc/Feed.php:133
Stack trace:
#0 /home/bas/XXXXXXXXXX/server/inc/GPodder.php(175): Feed->fetch()
#1 /home/bas/XXXXXXXXXX/server/inc/GPodder.php(222): GPodder->updateFeedForSubscription(6)
#2 /home/bas/XXXXXXXXXX/server/index.php(154): GPodder->updateAllFeeds()
#3 {main}
Array
(
    [0] => Array
        (
            [function] => {closure}
            [args] => Array
                (
                    [0] => LogicException Object
                        (
                            [message:protected] => Missing title for: https://feed.ausha.co/BG6gxT83Mk7l
                            [string:Exception:private] => LogicException: Missing title for: https://feed.ausha.co/BG6gxT83Mk7l in /home/bas/XXXXXXXXXX/server/inc/Feed.php:133
Stack trace:
#0 /home/bas/XXXXXXXXXX/server/inc/GPodder.php(175): Feed->fetch()
#1 /home/bas/XXXXXXXXXX/server/inc/GPodder.php(222): GPodder->updateFeedForSubscription(6)
#2 /home/bas/XXXXXXXXXX/server/index.php(154): GPodder->updateAllFeeds()
#3 {main}
                            [code:protected] => 0
                            [file:protected] => /home/bas/XXXXXXXXXX/server/inc/Feed.php
                            [line:protected] => 133
                            [trace:Exception:private] => Array
                                (
                                    [0] => Array
                                        (
                                            [file] => /home/bas/XXXXXXXXXX/server/inc/GPodder.php
                                            [line] => 175
                                            [function] => fetch
                                            [class] => Feed
                                            [type] => ->
                                            [args] => Array
                                                (
                                                )
                                        )

                                    [1] => Array
                                        (
                                            [file] => /home/bas/XXXXXXXXXX/server/inc/GPodder.php
                                            [line] => 222
                                            [function] => updateFeedForSubscription
                                            [class] => GPodder
                                            [type] => ->
                                            [args] => Array
                                                (
                                                    [0] => 6
                                                )
                                        )

                                    [2] => Array
                                        (
                                            [file] => /home/bas/XXXXXXXXXX/server/index.php
                                            [line] => 154
                                            [function] => updateAllFeeds
                                            [class] => GPodder
                                            [type] => ->
                                            [args] => Array
                                                (
                                                )
                                        )
                                )

                            [previous:Exception:private] => 
                        )
                )
        )
)
```

**Comment by zorglube** [comment]
@bohwaz

**Comment by bohwaz** [comment]
This feed returns a 403 error.

**Comment by bohwaz** [comment]
This feed returns a 403 error.

**Comment by zorglube** [comment]
Oh ! Sorry for bothering you.
