### ISSUE TITLE
ErrorException: SQLite3::prepare(): Unable to prepare statement on device creation with AntennaPod

### ISSUE THREAD

**Issue by zefanja** [kd2org/opodsync#61]
I installed opodsync today and wanted to test the sync with AntennaPod (v3.5.0f). I can log in with my credentials, but I can't create a new device or see existing devices.

This is the error I get:

```
2024-12-25 16:00:42 Got a POST request on api/2/devices/user1/antennapod_auf_pixel_7a.json
```

```
[25-Dec-2024 16:00:42 Europe/Berlin] ErrorException: SQLite3::prepare(): Unable to prepare statement: 1, near &quot;ON&quot;: syntax error in myserver/html/podcast.example.com/inc/DB.php:55
Stack trace:
#0 [internal function]: {closure}(2, 'SQLite3::prepar...', '/var/www/vhosts...', 55)
#1 myserver/html/podcast.example.com/inc/DB.php(55): SQLite3->prepare('INSERT INTO dev...')
#2 myserver/html/podcast.example.com/inc/DB.php(81): DB->prepare2('INSERT INTO dev...', Array)
#3 myserver/html/podcast.example.com/inc/DB.php(47): DB->simple('INSERT INTO dev...', Array)
#4 myserver/html/podcast.example.com/inc/API.php(431): DB->upsert('devices', Array, Array)
#5 myserver/html/podcast.example.com/inc/API.php(228): API->devices()
#6 myserver/html/podcast.example.com/inc/API.php(381): API->route()
#7 myserver/html/podcast.example.com/index.php(86): API->handleRequest()
#8 {main}
[25-Dec-2024 16:00:42 Europe/Berlin] ErrorException: SQLite3::prepare(): Unable to prepare statement: 1, near &quot;ON&quot;: syntax error in myserver/html/podcast.example.com/inc/DB.php:55
Stack trace:
#0 [internal function]: {closure}(2, 'SQLite3::prepar...', '/var/www/vhosts...', 55)
#1 myserver/html/podcast.example.com/inc/DB.php(55): SQLite3->prepare('INSERT INTO dev...')
#2 myserver/html/podcast.example.com/inc/DB.php(81): DB->prepare2('INSERT INTO dev...', Array)
#3 myserver/html/podcast.example.com/inc/DB.php(47): DB->simple('INSERT INTO dev...', Array)
#4 myserver/html/podcast.example.com/inc/API.php(431): DB->upsert('devices', Array, Array)
#5 myserver/html/podcast.example.com/inc/API.php(228): API->devices()
#6 myserver/html/podcast.example.com/inc/API.php(381): API->route()
#7 myserver/html/podcast.example.com/index.php(86): API->handleRequest()
#8 {main}
[25-Dec-2024 16:00:42 Europe/Berlin] Array
(
    [0] => Array
        (
            [function] => {closure}
            [args] => Array
                (
                    [0] => 2
                    [1] => SQLite3::prepare(): Unable to prepare statement: 1, near &quot;ON&quot;: syntax error
                    [2] => myserver/html/podcast.example.com/inc/DB.php
                    [3] => 55
                )

        )

    [1] => Array
        (
            [file] => myserver/html/podcast.example.com/inc/DB.php
            [line] => 55
            [function] => prepare
            [class] => SQLite3
            [object] => DB Object
                (
                    [statements:protected] => Array
                        (
                            [123d5d8619f9874788d32d4ec1ee0e34] => SQLite3Stmt Object
                                (
                                )

                            [f92c7840fbedabdface91470010ae5e3] => SQLite3Stmt Object
                                (
                                )

                            [6383a37be8ca152a2e3f89a74c066c4e] => SQLite3Stmt Object
                                (
                                )

                        )

                )

            [type] => ->
            [args] => Array
                (
                    [0] => INSERT INTO devices (deviceid, data, name, user) VALUES (:deviceid, :data, :name, :user) ON CONFLICT (deviceid, user) DO UPDATE SET deviceid = :deviceid, data = :data, name = :name, user = :user;
                )

        )

    [2] => Array
        (
            [file] => myserver/html/podcast.example.com/inc/DB.php
            [line] => 81
            [function] => prepare2
            [class] => DB
            [object] => DB Object
                (
                    [statements:protected] => Array
                        (
                            [123d5d8619f9874788d32d4ec1ee0e34] => SQLite3Stmt Object
                                (
                                )

                            [f92c7840fbedabdface91470010ae5e3] => SQLite3Stmt Object
                                (
                                )

                            [6383a37be8ca152a2e3f89a74c066c4e] => SQLite3Stmt Object
                                (
                                )

                        )

                )

            [type] => ->
            [args] => Array
                (
                    [0] => INSERT INTO devices (deviceid, data, name, user) VALUES (:deviceid, :data, :name, :user) ON CONFLICT (deviceid, user) DO UPDATE SET deviceid = :deviceid, data = :data, name = :name, user = :user;
                    [1] => Array
                        (
                            [deviceid] => antennapod_auf_pixel_7a
                            [data] => {"caption":"AntennaPod auf Pixel 7a","type":"mobile","subscriptions":0}
                            [name] => AntennaPod auf Pixel 7a
                            [user] => 1
                        )

                )

        )

    [3] => Array
        (
            [file] => myserver/html/podcast.example.com/inc/DB.php
            [line] => 47
            [function] => simple
            [class] => DB
            [object] => DB Object
                (
                    [statements:protected] => Array
                        (
                            [123d5d8619f9874788d32d4ec1ee0e34] => SQLite3Stmt Object
                                (
                                )

                            [f92c7840fbedabdface91470010ae5e3] => SQLite3Stmt Object
                                (
                                )

                            [6383a37be8ca152a2e3f89a74c066c4e] => SQLite3Stmt Object
                                (
                                )

                        )

                )

            [type] => ->
            [args] => Array
                (
                    [0] => INSERT INTO devices (deviceid, data, name, user) VALUES (:deviceid, :data, :name, :user) ON CONFLICT (deviceid, user) DO UPDATE SET deviceid = :deviceid, data = :data, name = :name, user = :user;
                    [1] => Array
                        (
                            [deviceid] => antennapod_auf_pixel_7a
                            [data] => {"caption":"AntennaPod auf Pixel 7a","type":"mobile","subscriptions":0}
                            [name] => AntennaPod auf Pixel 7a
                            [user] => 1
                        )

                )

        )

    [4] => Array
        (
            [file] => myserver/html/podcast.example.com/inc/API.php
            [line] => 431
            [function] => upsert
            [class] => DB
            [object] => DB Object
                (
                    [statements:protected] => Array
                        (
                            [123d5d8619f9874788d32d4ec1ee0e34] => SQLite3Stmt Object
                                (
                                )

                            [f92c7840fbedabdface91470010ae5e3] => SQLite3Stmt Object
                                (
                                )

                            [6383a37be8ca152a2e3f89a74c066c4e] => SQLite3Stmt Object
                                (
                                )

                        )

                )

            [type] => ->
            [args] => Array
                (
                    [0] => devices
                    [1] => Array
                        (
                            [deviceid] => antennapod_auf_pixel_7a
                            [data] => {"caption":"AntennaPod auf Pixel 7a","type":"mobile","subscriptions":0}
                            [name] => AntennaPod auf Pixel 7a
                            [user] => 1
                        )

                    [2] => Array
                        (
                            [0] => deviceid
                            [1] => user
                        )

                )

        )

    [5] => Array
        (
            [file] => myserver/html/podcast.example.com/inc/API.php
            [line] => 228
            [function] => devices
            [class] => API
            [object] => API Object
                (
                    [method:protected] => POST
                    [user:protected] => stdClass Object
                        (
                            [id] => 1
                            [name] => user1
                            [password] => mysupersecretpassword
                        )

                    [section:protected] => devices
                    [url] => api/2/devices/user1/antennapod_auf_pixel_7a.json
                    [base_url] => https://podcast.example.com/
                    [base_path] => /
                    [path:protected] => user1/antennapod_auf_pixel_7a
                    [format:protected] => json
                    [db:protected] => DB Object
                        (
                            [statements:protected] => Array
                                (
                                    [123d5d8619f9874788d32d4ec1ee0e34] => SQLite3Stmt Object
                                        (
                                        )

                                    [f92c7840fbedabdface91470010ae5e3] => SQLite3Stmt Object
                                        (
                                        )

                                    [6383a37be8ca152a2e3f89a74c066c4e] => SQLite3Stmt Object
                                        (
                                        )

                                )

                        )

                )

            [type] => ->
            [args] => Array
                (
                )

        )

    [6] => Array
        (
            [file] => myserver/html/podcast.example.com/inc/API.php
            [line] => 381
            [function] => route
            [class] => API
            [object] => API Object
                (
                    [method:protected] => POST
                    [user:protected] => stdClass Object
                        (
                            [id] => 1
                            [name] => user1
                            [password] => mysupersecretpassword
                        )

                    [section:protected] => devices
                    [url] => api/2/devices/user1/antennapod_auf_pixel_7a.json
                    [base_url] => https://podcast.example.com/
                    [base_path] => /
                    [path:protected] => user1/antennapod_auf_pixel_7a
                    [format:protected] => json
                    [db:protected] => DB Object
                        (
                            [statements:protected] => Array
                                (
                                    [123d5d8619f9874788d32d4ec1ee0e34] => SQLite3Stmt Object
                                        (
                                        )

                                    [f92c7840fbedabdface91470010ae5e3] => SQLite3Stmt Object
                                        (
                                        )

                                    [6383a37be8ca152a2e3f89a74c066c4e] => SQLite3Stmt Object
                                        (
                                        )

                                )

                        )

                )

            [type] => ->
            [args] => Array
                (
                )

        )

    [7] => Array
        (
            [file] => myserver/html/podcast.example.com/index.php
            [line] => 86
            [function] => handleRequest
            [class] => API
            [object] => API Object
                (
                    [method:protected] => POST
                    [user:protected] => stdClass Object
                        (
                            [id] => 1
                            [name] => user1
                            [password] => mysupersecretpassword
                        )

                    [section:protected] => devices
                    [url] => api/2/devices/user1/antennapod_auf_pixel_7a.json
                    [base_url] => https://podcast.example.com/
                    [base_path] => /
                    [path:protected] => user1/antennapod_auf_pixel_7a
                    [format:protected] => json
                    [db:protected] => DB Object
                        (
                            [statements:protected] => Array
                                (
                                    [123d5d8619f9874788d32d4ec1ee0e34] => SQLite3Stmt Object
                                        (
                                        )

                                    [f92c7840fbedabdface91470010ae5e3] => SQLite3Stmt Object
                                        (
                                        )

                                    [6383a37be8ca152a2e3f89a74c066c4e] => SQLite3Stmt Object
                                        (
                                        )

                                )

                        )

                )

            [type] => ->
            [args] => Array
                (
                )

        )

)
```

If I choose the Nextcloud option in AntennaPod, I can login, but syncing fails with the same error.

**Comment by bohwaz** [comment]
I think you have a version of SQLite that is too old. ON CONFLICT cause was introduced 8 years ago in SQLite 3.24.

You should upgrade your version of SQLite, it should solve it.

**Comment by zefanja** [comment]
Thanks...I'll contact my webhoster.
